/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OwnerLoginRouteImport } from './routes/owner-login'
import { Route as OwnerForgotPasswordRouteImport } from './routes/owner-forgot-password'
import { Route as OwnerDashboardRouteImport } from './routes/owner-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as ApiCommentsApprovedRouteImport } from './routes/api/comments/approved'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerLoginRoute = OwnerLoginRouteImport.update({
  id: '/owner-login',
  path: '/owner-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerForgotPasswordRoute = OwnerForgotPasswordRouteImport.update({
  id: '/owner-forgot-password',
  path: '/owner-forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner-dashboard',
  path: '/owner-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsApprovedRoute = ApiCommentsApprovedRouteImport.update({
  id: '/api/comments/approved',
  path: '/api/comments/approved',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/owner-forgot-password': typeof OwnerForgotPasswordRoute
  '/owner-login': typeof OwnerLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/comments/approved': typeof ApiCommentsApprovedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/owner-forgot-password': typeof OwnerForgotPasswordRoute
  '/owner-login': typeof OwnerLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/comments/approved': typeof ApiCommentsApprovedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/owner-dashboard': typeof OwnerDashboardRoute
  '/owner-forgot-password': typeof OwnerForgotPasswordRoute
  '/owner-login': typeof OwnerLoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/api/comments/approved': typeof ApiCommentsApprovedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/owner-dashboard'
    | '/owner-forgot-password'
    | '/owner-login'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/chat'
    | '/api/comments/approved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/owner-dashboard'
    | '/owner-forgot-password'
    | '/owner-login'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/chat'
    | '/api/comments/approved'
  id:
    | '__root__'
    | '/'
    | '/owner-dashboard'
    | '/owner-forgot-password'
    | '/owner-login'
    | '/sitemap.xml'
    | '/admin/dashboard'
    | '/admin/login'
    | '/api/chat'
    | '/api/comments/approved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerForgotPasswordRoute: typeof OwnerForgotPasswordRoute
  OwnerLoginRoute: typeof OwnerLoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiCommentsApprovedRoute: typeof ApiCommentsApprovedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-login': {
      id: '/owner-login'
      path: '/owner-login'
      fullPath: '/owner-login'
      preLoaderRoute: typeof OwnerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-forgot-password': {
      id: '/owner-forgot-password'
      path: '/owner-forgot-password'
      fullPath: '/owner-forgot-password'
      preLoaderRoute: typeof OwnerForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner-dashboard': {
      id: '/owner-dashboard'
      path: '/owner-dashboard'
      fullPath: '/owner-dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments/approved': {
      id: '/api/comments/approved'
      path: '/api/comments/approved'
      fullPath: '/api/comments/approved'
      preLoaderRoute: typeof ApiCommentsApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerForgotPasswordRoute: OwnerForgotPasswordRoute,
  OwnerLoginRoute: OwnerLoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
  ApiCommentsApprovedRoute: ApiCommentsApprovedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
