-- supabase/migrations/20260913000000_init.sql

-- Enable pgcrypto for UUIDs
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. site_settings
CREATE TABLE IF NOT EXISTS public.site_settings (
  id boolean PRIMARY KEY DEFAULT true,
  resume_url text,
  email text,
  phone_display text,
  phone_tel text,
  linkedin_url text,
  github_url text,
  hero_name text,
  hero_subtitles text[],
  hero_bio text,
  hero_code_card jsonb,
  about_paragraphs text[],
  about_focus_areas text[],
  CONSTRAINT site_settings_single_row CHECK (id = true)
);

-- 2. skills
CREATE TABLE IF NOT EXISTS public.skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name text NOT NULL,
  name text NOT NULL,
  level integer NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 3. projects
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  tag text,
  description text,
  tech text[],
  icon_name text,
  accent_class text,
  is_embedded boolean DEFAULT false,
  display_order integer NOT NULL DEFAULT 0
);

-- 4a. experience
CREATE TABLE IF NOT EXISTS public.experience (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  company text NOT NULL,
  period text NOT NULL,
  location text NOT NULL,
  is_current boolean DEFAULT false,
  bullets text[] NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 4b. education
CREATE TABLE IF NOT EXISTS public.education (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  institution text NOT NULL,
  score text NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 5. services
CREATE TABLE IF NOT EXISTS public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 6. why_hire_reasons
CREATE TABLE IF NOT EXISTS public.why_hire_reasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  display_order integer NOT NULL DEFAULT 0
);

-- 7. achievements
CREATE TABLE IF NOT EXISTS public.achievements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  value text NOT NULL,
  suffix text,
  display_order integer NOT NULL DEFAULT 0
);

-- 8. certifications
CREATE TABLE IF NOT EXISTS public.certifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  platform text NOT NULL,
  date text,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 9. marquee_items
CREATE TABLE IF NOT EXISTS public.marquee_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  display_order integer NOT NULL DEFAULT 0
);

-- 10. messages (Comments and Contact Forms)
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  subject text,
  message text NOT NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'hidden')),
  is_pinned boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  moderated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

-- 11. chat_logs (AI chatbot logs)
CREATE TABLE IF NOT EXISTS public.chat_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_query text NOT NULL,
  bot_response text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Row Level Security (RLS) setup

-- Enable RLS on all tables
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.why_hire_reasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marquee_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

-- Helper function to check if user is owner
CREATE OR REPLACE FUNCTION public.is_owner()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT (auth.jwt() ->> 'email')::text = 'email_Address_of_owner';
$$;
