-- supabase/migrations/20260913000000_init.sql

-- Enable pgcrypto for UUIDs
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- 1. site_settings
CREATE TABLE IF NOT EXISTS public.site_settings (
  id boolean PRIMARY KEY DEFAULT true,
  resume_url text,
  email text,
  phone_display text,
  phone_tel text,
  linkedin_url text,
  github_url text,
  hero_name text,
  hero_subtitles text[],
  hero_bio text,
  hero_code_card jsonb,
  about_paragraphs text[],
  about_focus_areas text[],
  CONSTRAINT site_settings_single_row CHECK (id = true)
);

-- 2. skills
CREATE TABLE IF NOT EXISTS public.skills (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_name text NOT NULL,
  name text NOT NULL,
  level integer NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 3. projects
CREATE TABLE IF NOT EXISTS public.projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  tag text,
  description text,
  tech text[],
  icon_name text,
  accent_class text,
  is_embedded boolean DEFAULT false,
  display_order integer NOT NULL DEFAULT 0
);

-- 4a. experience
CREATE TABLE IF NOT EXISTS public.experience (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  company text NOT NULL,
  period text NOT NULL,
  location text NOT NULL,
  is_current boolean DEFAULT false,
  bullets text[] NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 4b. education
CREATE TABLE IF NOT EXISTS public.education (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  institution text NOT NULL,
  score text NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 5. services
CREATE TABLE IF NOT EXISTS public.services (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 6. why_hire_reasons
CREATE TABLE IF NOT EXISTS public.why_hire_reasons (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  description text NOT NULL,
  display_order integer NOT NULL DEFAULT 0
);

-- 7. achievements
CREATE TABLE IF NOT EXISTS public.achievements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  label text NOT NULL,
  value text NOT NULL,
  suffix text,
  display_order integer NOT NULL DEFAULT 0
);

-- 8. certifications
CREATE TABLE IF NOT EXISTS public.certifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  platform text NOT NULL,
  date text,
  icon_name text,
  display_order integer NOT NULL DEFAULT 0
);

-- 9. marquee_items
CREATE TABLE IF NOT EXISTS public.marquee_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text NOT NULL,
  display_order integer NOT NULL DEFAULT 0
);

-- 10. messages (Comments and Contact Forms)
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  email text,
  subject text,
  message text NOT NULL,
  status text DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'hidden')),
  is_pinned boolean DEFAULT false,
  is_featured boolean DEFAULT false,
  moderated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now()
);

-- 11. chat_logs (AI chatbot logs)
CREATE TABLE IF NOT EXISTS public.chat_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_query text NOT NULL,
  bot_response text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Row Level Security (RLS) setup

-- Enable RLS on all tables
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.experience ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.education ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.why_hire_reasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.certifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marquee_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

-- Helper function to check if user is owner
CREATE OR REPLACE FUNCTION public.is_owner()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT (auth.jwt() ->> 'email')::text = 'ganeshkaithoju4685@gmail.com';
$$;

-- Public Read Access Policies

DROP POLICY IF EXISTS "Public read site_settings" ON public.site_settings;
CREATE POLICY "Public read site_settings"
ON public.site_settings
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read skills" ON public.skills;
CREATE POLICY "Public read skills"
ON public.skills
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read projects" ON public.projects;
CREATE POLICY "Public read projects"
ON public.projects
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read experience" ON public.experience;
CREATE POLICY "Public read experience"
ON public.experience
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read education" ON public.education;
CREATE POLICY "Public read education"
ON public.education
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read services" ON public.services;
CREATE POLICY "Public read services"
ON public.services
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read why_hire_reasons" ON public.why_hire_reasons;
CREATE POLICY "Public read why_hire_reasons"
ON public.why_hire_reasons
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read achievements" ON public.achievements;
CREATE POLICY "Public read achievements"
ON public.achievements
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read certifications" ON public.certifications;
CREATE POLICY "Public read certifications"
ON public.certifications
FOR SELECT
USING (true);

DROP POLICY IF EXISTS "Public read marquee_items" ON public.marquee_items;
CREATE POLICY "Public read marquee_items"
ON public.marquee_items
FOR SELECT
USING (true);


-- Public Read for Messages (Only approved)

DROP POLICY IF EXISTS "Public read approved messages" ON public.contact_messages;
CREATE POLICY "Public read approved messages"
ON public.contact_messages
FOR SELECT
USING (status = 'approved');


-- Public Insert for Messages (Contact form/comments)

DROP POLICY IF EXISTS "Public insert messages" ON public.contact_messages;
CREATE POLICY "Public insert messages"
ON public.contact_messages
FOR INSERT
WITH CHECK (true);


-- Owner Full Access Policies (CMS)

DROP POLICY IF EXISTS "Owner full access site_settings" ON public.site_settings;
CREATE POLICY "Owner full access site_settings"
ON public.site_settings
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access skills" ON public.skills;
CREATE POLICY "Owner full access skills"
ON public.skills
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access projects" ON public.projects;
CREATE POLICY "Owner full access projects"
ON public.projects
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access experience" ON public.experience;
CREATE POLICY "Owner full access experience"
ON public.experience
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access education" ON public.education;
CREATE POLICY "Owner full access education"
ON public.education
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access services" ON public.services;
CREATE POLICY "Owner full access services"
ON public.services
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access why_hire_reasons" ON public.why_hire_reasons;
CREATE POLICY "Owner full access why_hire_reasons"
ON public.why_hire_reasons
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access achievements" ON public.achievements;
CREATE POLICY "Owner full access achievements"
ON public.achievements
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access certifications" ON public.certifications;
CREATE POLICY "Owner full access certifications"
ON public.certifications
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access marquee_items" ON public.marquee_items;
CREATE POLICY "Owner full access marquee_items"
ON public.marquee_items
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access messages" ON public.contact_messages;
CREATE POLICY "Owner full access messages"
ON public.contact_messages
FOR ALL
TO authenticated
USING (public.is_owner());

DROP POLICY IF EXISTS "Owner full access chat_logs" ON public.chat_logs;
CREATE POLICY "Owner full access chat_logs"
ON public.chat_logs
FOR ALL
TO authenticated
USING (public.is_owner());

-- Storage bucket (Assuming you create this in the dashboard, but you can also do it via SQL if pgsodium is installed. Best practice is to create it via SQL if possible)
INSERT INTO storage.buckets (id, name, public) VALUES ('portfolio-assets', 'portfolio-assets', true) ON CONFLICT (id) DO NOTHING;

-- Storage RLS

DROP POLICY IF EXISTS "Public read portfolio-assets" ON storage.objects;
CREATE POLICY "Public read portfolio-assets"
ON storage.objects
FOR SELECT
USING (bucket_id = 'portfolio-assets');

DROP POLICY IF EXISTS "Owner full access portfolio-assets" ON storage.objects;
CREATE POLICY "Owner full access portfolio-assets"
ON storage.objects
FOR ALL
TO authenticated
USING (
  bucket_id = 'portfolio-assets'
  AND public.is_owner()
);

-- SEED DATA (from index.tsx)

INSERT INTO public.site_settings (
  id, resume_url, email, phone_display, phone_tel, linkedin_url, github_url, 
  hero_name, hero_subtitles, hero_bio, hero_code_card, about_paragraphs, about_focus_areas
) VALUES (
  true, 
  '/src/assets/resume.pdf', 
  'ganeshkaithoju4685@gmail.com', 
  '+91 93923 79339', 
  '+919392379339', 
  'https://www.linkedin.com/in/ganesh-kaithoju', 
  'https://github.com/Ganeshkaithoju',
  'Ganesh', 
  ARRAY['full-stack web apps', 'clean interfaces', 'reliable systems', 'IoT that ships'],
  'Aspiring Software & Full-Stack Developer working with HTML, CSS, JavaScript, React, Python, Java and Spring Boot. Currently interning on the Backup & Restore team at Lumen Technologies India.',
  '{"name": "Kaithoju Ganesh", "role": "Software & Full-Stack Dev", "stack": ["React", "Node", "Python", "Java", "Spring Boot", "MySQL"], "focus": "reliable · elegant · fast", "cgpa": 8.42, "now": "Intern @ Lumen — Backup & Restore", "shipping": true}',
  ARRAY[
    'I''m Kaithoju Ganesh, an aspiring Software & Full-Stack Developer pursuing my B.Tech in Electronics & Communication Engineering at Narasimha Reddy Engineering College.',
    'I enjoy building dynamic, responsive, user-friendly applications — from React front-ends to Java / Spring Boot APIs and MySQL back-ends — and I''m equally at home with Arduino, NodeMCU and Embedded C.',
    'Right now I''m an Intern on the Backup & Restore team at Lumen Technologies India, learning enterprise engineering practices and shipping alongside a real product team.',
    'Outside of coursework I love turning ideas into working prototypes — automating irrigation, building assistive devices, and shipping full-stack side projects.'
  ],
  ARRAY['Full-Stack Development', 'Backend & APIs', 'Database Design', 'Embedded / IoT', 'Python Automation', 'Data Structures & OOP']
) ON CONFLICT (id) DO NOTHING;

INSERT INTO public.skills (group_name, name, level, icon_name, display_order) VALUES
  ('Frontend', 'HTML5', 94, 'Layers', 1),
  ('Frontend', 'CSS3', 90, 'Layers', 2),
  ('Frontend', 'JavaScript', 86, 'Layers', 3),
  ('Frontend', 'React', 84, 'Layers', 4),
  ('Backend', 'Python', 88, 'Server', 5),
  ('Backend', 'Java', 82, 'Server', 6),
  ('Backend', 'Spring Boot', 78, 'Server', 7),
  ('Backend', 'Node.js', 72, 'Server', 8),
  ('Database', 'MySQL', 84, 'Database', 9),
  ('Languages & Concepts', 'C', 78, 'Terminal', 10),
  ('Languages & Concepts', 'OOP', 88, 'Terminal', 11),
  ('Languages & Concepts', 'DSA', 80, 'Terminal', 12),
  ('Languages & Concepts', 'DBMS', 82, 'Terminal', 13),
  ('Embedded / IoT', 'Arduino UNO', 85, 'CircuitBoard', 14),
  ('Embedded / IoT', 'NodeMCU (ESP8266)', 80, 'CircuitBoard', 15),
  ('Embedded / IoT', 'Embedded C', 78, 'CircuitBoard', 16),
  ('Embedded / IoT', 'Sensors & Actuators', 82, 'CircuitBoard', 17),
  ('Tools', 'Git & GitHub', 84, 'Wrench', 18),
  ('Tools', 'VS Code', 94, 'Wrench', 19),
  ('Tools', 'UiPath (RPA)', 72, 'Wrench', 20);

INSERT INTO public.projects (title, tag, description, tech, icon_name, accent_class, is_embedded, display_order) VALUES
  ('Smart Agriculture Decision Support System', 'IoT · Embedded', 'Automated irrigation using real-time soil-moisture and water-level monitoring. Arduino UNO + NodeMCU control a water pump with sensor-based decision logic and alert mechanisms, reducing water wastage and supporting sustainable crop management.', ARRAY['Arduino UNO', 'NodeMCU (ESP8266)', 'Embedded C', 'Sensors'], 'Leaf', 'from-emerald-400 to-teal-500', true, 1),
  ('Spoonie — Self-Stabilizing Feeding Spoon', 'Assistive Tech', 'Self-stabilizing feeding spoon that assists people with hand tremors. Integrates an ADXL345 accelerometer with servo motors for real-time tremor detection and motion compensation, driven by Embedded C.', ARRAY['Arduino UNO', 'ADXL345', 'Servo Motor', 'Embedded C'], 'Utensils', 'from-amber-400 to-orange-500', true, 2),
  ('Hospital Management System', 'Full Stack', 'Hospital portal for patient registration, doctor scheduling, billing and reports. Role-based dashboards for admins, medical staff and customers with a clean, responsive UI.', ARRAY['React', 'Spring Boot', 'MySQL'], 'Hospital', 'from-sky-400 to-indigo-500', false, 3),
  ('Subscription Management System', 'Full Stack', 'Responsive subscription and billing web app with admin and user dashboards. Client-side routing, role-based auth, and plan/user/subscription management — production-ready UI built to scale.', ARRAY['React.js', 'Node.js'], 'CreditCard', 'from-fuchsia-400 to-purple-500', false, 4);

INSERT INTO public.experience (title, company, period, location, is_current, bullets, icon_name, display_order) VALUES
  ('Intern — Backup & Restore', 'Lumen Technologies India', '2026 — Present', 'Bengaluru, IN', true, ARRAY['Working with the Backup & Restore team on enterprise data-protection workflows', 'Learning production-grade backup/restore tooling, monitoring and troubleshooting', 'Collaborating within an Agile team — standups, sprints, code reviews', 'Sharpening scripting and debugging skills against real infrastructure'], 'HardDrive', 1),
  ('Summer Intern', 'BHEL — Bharat Heavy Electricals Limited', 'May 2025 — June 2025', 'Hyderabad, IN', false, ARRAY['Team member on a thermal power systems project', 'Analyzed PLC and CNC processes on the shop floor', 'Hands-on exposure to industrial automation and cross-functional teamwork'], 'Briefcase', 2),
  ('Python Intern', 'YBI Foundation', 'March 2025 — April 2025', 'Remote', false, ARRAY['Learned core Python concepts and standard libraries', 'Built projects like Tic-Tac-Toe and Rock-Paper-Scissors', 'Strengthened programming fundamentals and problem-solving'], 'Terminal', 3);

INSERT INTO public.education (title, institution, score, icon_name, display_order) VALUES
  ('B.Tech — Electronics & Communication', 'Narasimha Reddy Engineering College · 2022 – 2026', 'CGPA 8.42 / 10', 'GraduationCap', 1),
  ('Intermediate', 'Trinity Junior College, Karimnagar · 2020 – 2022', '83.9%', 'GraduationCap', 2),
  ('SSC', 'Z.P.H.S Chimanpally, Nizamabad · 2019 – 2020', 'CGPA 10 / 10', 'GraduationCap', 3);

INSERT INTO public.services (title, description, icon_name, display_order) VALUES
  ('Web Development', 'End-to-end responsive websites tailored to your brand.', 'Globe', 1),
  ('Frontend Development', 'Clean UIs with React, HTML, CSS and modern tooling.', 'Layers', 2),
  ('Backend Development', 'REST APIs with Java, Spring Boot and Node.js.', 'Server', 3),
  ('Python Development', 'Automation, scripting and data-driven applications.', 'Cpu', 4),
  ('Embedded / IoT', 'Arduino & NodeMCU projects with sensors and actuators.', 'CircuitBoard', 5),
  ('Database Design', 'MySQL schemas that scale with your product.', 'Database', 6),
  ('API Development', 'Fast, secure and well-documented REST APIs.', 'Zap', 7),
  ('Responsive Design', 'Mobile-first, accessible, delightful on every screen.', 'Sparkles', 8);

INSERT INTO public.why_hire_reasons (title, description, display_order) VALUES
  ('Problem Solver', 'Break big problems into small, testable steps.', 1),
  ('Team Collaboration', 'Communicate clearly, review kindly, ship together.', 2),
  ('Adaptability', 'Comfortable jumping across the stack and picking up new tools.', 3),
  ('Continuous Learner', 'Always a new doc, a new language, a new pattern to learn.', 4),
  ('Strong Fundamentals', 'OOP, DSA, DBMS — a well-rounded CS/ECE base.', 5),
  ('Hands-on Builder', 'Full-stack, embedded, and hardware — I love making things work.', 6),
  ('Clear Communicator', 'Structured writing, on-time updates, no surprises.', 7),
  ('Craft-driven', 'I care how the code reads, not just how it runs.', 8);

INSERT INTO public.achievements (label, value, suffix, display_order) VALUES
  ('B.Tech CGPA', '8.42', '/10', 1),
  ('SSC CGPA', '10', '/10', 2),
  ('Projects', '4', '+', 3),
  ('Certifications', '10', '+', 4);

INSERT INTO public.certifications (title, platform, date, icon_name, display_order) VALUES
  ('Robotic Process Automation using UiPath', 'Infosys Foundation — Finishing School for Employability', 'July 2025', 'Shield', 1),
  ('Remote Sensing Data Analytics for Crop Production Forecasting', 'ISRO', '31 July 2025', 'Award', 2),
  ('Python Internship Certificate', 'YBI Foundation', '10 April 2025', 'Terminal', 3),
  ('Java Basic Certificate', 'HackerRank', '01 November 2024', 'Code2', 4);

INSERT INTO public.marquee_items (text, display_order) VALUES
  ('Python', 1),
  ('Java', 2),
  ('React', 3),
  ('Spring Boot', 4),
  ('MySQL', 5),
  ('HTML', 6),
  ('CSS', 7),
  ('JavaScript', 8),
  ('Arduino', 9),
  ('NodeMCU', 10),
  ('Embedded C', 11),
  ('Git', 12),
  ('UiPath', 13),
  ('REST APIs', 14),
  ('OOP', 15);
